### ISSUE TITLE
lightstep-opentelemetry-exporter depends on an older version of opentelemetry

### ISSUE THREAD

**Issue by kirbysayshi** [lightstep/opentelemetry-exporter-js#11]
From a recent `yarn add lighstep-opentelemetry-exporter`:

```
warning lightstep-opentelemetry-exporter > @opentelemetry/base@0.6.1: The package has been merged to @opentelemetry/core. Update your package.json.
warning lightstep-opentelemetry-exporter > @opentelemetry/tracing > @opentelemetry/base@0.6.1: The package has been merged to @opentelemetry/core. Update your package.json.
warning lightstep-opentelemetry-exporter > @opentelemetry/tracing > @opentelemetry/resources > @opentelemetry/base@0.6.1: The package has been merged to @opentelemetry/core. Update your package.json.
```

The current version of `@opentelemetry/api` is 0.9.0, so this means that to use opentelemetry with lightstep I have two options:

- pin the version to 0.9.0 and hope it's compatible 
- use 0.6.* of opentelemetry

Neither are really ideal, since using an older version will be difficult to debug, and I won't be able to get bug fixes. Also, I'm not sure I can even pin opentelemetry to 0.9 if the modules have changed (base -> core).

Are there plans to merge this exporter into the opentelemetry repo, or to keep this updated with opentelemetry's major versions?

**Comment by kayousterhout** [comment]
We're planning to deprecate this exporter by the end of the month, in favor of using the OTLP exporter that's in open telemetry (we don't recommend using the OTLP exporter quite yet because there was a breaking change in the OTLP protocol, and the satellite release to support the latest OTLP proto isn't out yet).  Let us know how that works with your timeline - if that's prohibitively long to wait, we can update this exporter to the latest.

**Comment by kirbysayshi** [comment]
@kayousterhout thanks for the info!

If OTLP is going to be supported and available by the end of the month (and updating satellites is low effort?) then I can definitely wait.

**Comment by andrewhsu** [comment]
closing this issue because this repo is now archived
